services:
  zara-db:
    image: postgres:latest
    restart: always
    ports:
      - "6644:6644"
    env_file:
      - backend/.env
    volumes:
      - db_data:/var/lib/postgresql/data
    command:  ["postgres", "-p", "6644"]

volumes:
  db_data: