services:
  zara-db:
    image: postgres:latest
    restart: always
    ports:
      - "6644:6644"
    env_file:
      - backend/.env
    networks:
      - zara
    volumes:
      - db_data:/var/lib/postgresql/data
    command:  ["postgres", "-p", "6644"]
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9091:9091"
    volumes:
      - minio-data:/data
    networks:
      - zara
    env_file:
      - backend/.env
    command: server /data --console-address ":9091"
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    ports:
      - "6789:6789"
    networks:
      - zara
    depends_on:
      - minio
      - zara-db
  frontend-dev:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
      args:
        - VITE_GENERATE_SOURCEMAP=${VITE_GENERATE_SOURCEMAP}
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - frontend/.env
    networks:
      - zara
#  frontend-prod:
#    build:
#      context: frontend
#      dockerfile: Dockerfile
#      args:
#        - VITE_GENERATE_SOURCEMAP=${VITE_GENERATE_SOURCEMAP}
#    ports:
#      - "3000:80"
#    env_file:
#      - frontend/.env
#    networks:
#      - zara

volumes:
  db_data:
  minio-data:
  node_modules:

networks:
  zara: