spring:
  application:
    name: backend
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
        mail:
            smtp:
              auth: true
              starttls:
                  enable: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
  web:
    resources:
      add-mappings: false
server:
  port: 6789
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-binding-errors: always
minio:
  url: ${MINIO_ENDPOINT}
  access:
    name: ${MINIO_ROOT_USER}
    secret: ${MINIO_ROOT_PASSWORD}
  bucket:
    name: zara
app:
  jwt:
    secret: ${JWT_SECRET_KEY}
    expires-in: 24
  cookie:
    name: authToken
    expires-in: 24
logging:
  level:
    org:
      springframework:
        security:
            web:
                filter:
                security:
                    AuthenticationFilter: DEBUG
                    FilterChainProxy: DEBUG
