spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:6644}/${POSTGRES_DB:zara}
    username: ${POSTGRES_USER:zara}
    password: ${POSTGRES_PASSWORD:zara}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true



